import type { NextPage } from "next";
import { observer } from "mobx-react-lite";
import Head from "next/head";
import {
  Box,
  Img,
  Heading,
  Input,
  InputGroup,
  InputRightElement,
  Icon,
  Text,
  Container,
  Flex,
} from "@chakra-ui/react";

import Bg from "../assets/bg.jpg";

import { Search } from "../ui/icons/menu";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Fishing - Main</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box pos="relative">
        <Box
          pos="absolute"
          top={0}
          left={0}
          w="100%"
          h="100%"
          bg="rgba(0,0,0,.25)"
          display="flex"
          alignItems="center"
          justifyContent="center"
          flexDir="column"
        >
          <Heading textTransform="uppercase" color="white" mb={6}>
            Fishing
          </Heading>
          <Box>
            <InputGroup>
              <Input
                color="white"
                w="300px"
                placeholder="Найди водоем"
                _placeholder={{ color: "white" }}
              />
              <InputRightElement zIndex={6}>
                <Box cursor="pointer">
                  <Search color="white" />
                </Box>
              </InputRightElement>
            </InputGroup>
          </Box>
        </Box>
        <Img
          src={Bg.src}
          objectFit="cover"
          h="600px"
          w="100%"
          objectPosition="center"
        />
      </Box>

      <Box mt={6}>
        <Container maxW="1280" textAlign="center">
          <Heading as="h2" mb={4}>
            О чем этот проект
          </Heading>
          <Text>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam
            corporis voluptatem quae dicta perferendis. Sit, cupiditate laborum.
            Aut, eaque doloremque veniam excepturi, repellat in, magni a
            architecto explicabo earum assumenda! Lorem ipsum dolor sit amet
            consectetur adipisicing elit. Accusamus, consequuntur voluptate,
            corrupti quisquam tenetur at obcaecati, dolorum neque laborum
            necessitatibus vero libero perferendis vitae corporis dolorem
            dolores delectus nam! Culpa.
          </Text>

          <Flex alignItems="center" justifyContent="space-between" my={8}>
            <Box
              h="200px"
              w="200px"
              borderRadius="50px"
              bg="#f0f0f3"
              boxShadow="10px 10px 21px #d3d3d6,-10px -10px 21px #fff"
            ></Box>
            <Box
              h="200px"
              w="200px"
              borderRadius="50px"
              bg="#f0f0f3"
              boxShadow="10px 10px 21px #d3d3d6,-10px -10px 21px #fff"
            ></Box>
            <Box
              h="200px"
              w="200px"
              borderRadius="50px"
              bg="#f0f0f3"
              boxShadow="10px 10px 21px #d3d3d6,-10px -10px 21px #fff"
            ></Box>
          </Flex>
        </Container>

        <Box h="300px"></Box>
      </Box>
    </Box>
  );
};

export default observer(Home);
